Repository Deltares/HYDROLIB-core, pull requests merged in 2022-11, with the labels that each got.

#404 Update .gitignore
  .gitignore
Labels: chore

#407 #308: Change data block default spacing from 4 to 2
  hydrolib/core/io/dflowfm/ini/serializer.py
  tests/data/reference/bc/FlowFM_boundaryconditions2d_and_vectors.bc
  tests/data/reference/bc/FlowFM_boundaryconditions3d_and_vectors.bc
  tests/data/reference/bc/test.bc
  tests/io/dflowfm/ini/test_ini.py
Labels: enhancement

#418 #258: Move the base module in XYZ to IO (does not belong in dflowfm.xyz)
  hydrolib/core/basemodel.py
  hydrolib/core/io/base.py
Labels: refactor
