Repository Deltares/HYDROLIB-core, pull requests merged in 2025-05, with the labels that each got.

#776 Extended list of meshkernel arguments to be passed through hydrolib-core from hydrolib-dhydamo
  hydrolib/core/dflowfm/net/models.py
  tests/dflowfm/test_net.py
Labels: type: feature, domain: mesh

#800 Solve Sonar Cloud issues in (feat: external forcings converter #647)
  hydrolib/core/basemodel.py
  hydrolib/core/baseparser.py
  hydrolib/core/dflowfm/cmp/models.py
  hydrolib/core/dflowfm/cmp/parser.py
  hydrolib/core/dflowfm/ext/models.py
  hydrolib/core/dflowfm/research/models.py
  hydrolib/core/dflowfm/t3d/models.py
  hydrolib/core/dflowfm/t3d/parser.py
  hydrolib/core/dflowfm/tim/models.py
  hydrolib/core/dflowfm/tim/parser.py
  hydrolib/tools/extforce_convert/cli.py
  hydrolib/tools/extforce_convert/converters.py
  hydrolib/tools/extforce_convert/main_converter.py
  hydrolib/tools/extforce_convert/mdu_parser.py
  tests/dflowfm/bc/test_forcing_model.py
  tests/dflowfm/test_cmp.py
  tests/dflowfm/test_tim.py
  tests/tools/test_converters.py
  tests/tools/test_mdu_parser.py
Labels: type: enhancement, type: refactor

#805 Remove exclude unset option from _save method
  hydrolib/core/basemodel.py
  hydrolib/core/dflowfm/t3d/models.py
  hydrolib/core/dflowfm/tim/models.py
  hydrolib/tools/extforce_convert/main_converter.py
  pyproject.toml
Labels: type: bug

#807 Docs/746 rearrange cli docs
  docs/tutorials/extforce-convert/external_forcing_conversion.md
  mkdocs.yml
Labels: type: documentation

#813 Task/812-Refactor the MDU functionalities
  hydrolib/tools/extforce_convert/main_converter.py
  hydrolib/tools/extforce_convert/mdu_parser.py
  pyproject.toml
  tests/tools/test_converter_boundary_condition.py
  tests/tools/test_converters_source_sink.py
  tests/tools/test_main_converter.py
  tests/tools/test_mdu_parser.py
Labels: type: refactor

#819 remove hard coded version
  tests/tools/test_cmp_to_bc.py
  tests/tools/test_tim_to_bc.py
  tests/utils.py
Labels: type: bug

#820 Extend CrossLocModel to accept one cross-section
  hydrolib/core/dflowfm/crosssection/models.py
  pyproject.toml
  tests/dflowfm/test_crosssection.py
Labels: type: feature

#826 refactor dimr functionalities
  hydrolib/core/dimr/models.py
  hydrolib/core/dimr/parser.py
  hydrolib/core/dimr/serializer.py
  pyproject.toml
  tests/test_model.py
Labels: type: refactor

#828 Add `verbose` argument to the polyline class (#550)
  docs/reference/polyfile.md
  hydrolib/core/dflowfm/polyfile/models.py
  hydrolib/core/dflowfm/polyfile/parser.py
  tests/dflowfm/polyfile/test_polyfile.py
  tests/dflowfm/polyfile/test_polyfile_parser.py
Labels: type: refactor

#830 update fm_container CI pipeline deprecated syntax
  .github/workflows/integration.yml
Labels: type: ci/cd

#845 Migrate `structure` module to pydantic v2
  .github/workflows/ci.yml
  hydrolib/core/base/models.py
  hydrolib/core/dflowfm/ini/models.py
  hydrolib/core/dflowfm/ini/util.py
  hydrolib/core/dflowfm/inifield/models.py
  hydrolib/core/dflowfm/storagenode/models.py
  hydrolib/core/dflowfm/structure/models.py
  tests/dflowfm/bc/__init__.py
  tests/dflowfm/structure/__init__.py
  tests/dflowfm/structure/test_general_structure.py
  tests/dflowfm/structure/test_pump_dam_break.py
  tests/dflowfm/structure/test_rest_structures.py
  tests/dflowfm/structure/test_structure.py
  tests/dflowfm/test_structure.py
Labels: dependencies
